// TaleofChaThai — authored field maps for the 5 endgame_route regions (docs §2.2/§7 item 4).
// Each screen is 24x32 tiles at 32px (768x1024 art). Tile legend (same as ChaThaiTheCat):
//   P = path/floor (walkable, safe)   G = grass/snow (walkable, encounter roll)
//   C = rocky/crystal floor (walkable, encounter roll)   W = water/lava/void-pool (blocked)
//   T = wall/tree/cliff/building (blocked)
// Grids are hand-authored approximations of the major features visible in each pixel-art map
// (path spine, lakes, plazas, buildings) — refined per-tile later if walk-testing finds snags.
'use strict';

const TILE_PX = 32;
const FIELD_VIEW_W = 15;
const FIELD_VIEW_H = 10;
const WALKABLE_TILES = 'PGC';
const ENCOUNTER_TILES = 'GC';

const FIELD_MAPS = {
  // ---------- NORMAL — Central Meadowcross ----------
  normal_1: {
    id: 'normal_1', name: 'Meadowcross Village', region: 'normal',
    width: 24, height: 32, bg: 'assets/region-maps/type/normal/meadowcross-village/meadowcross-village.png',
    entry: { x: 11, y: 29 },
    ground: [
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGTTTTTGGGPPGGGTTTTTGGT',
      'TGGTTTTTGGGPPGGGTTTTTGGT',
      'TGGTTTTTGPPPPPPGTTTTTGGT',
      'TGGGGGGGGPGGGGPGGGGGGGGT',
      'TGGGGGGGGPGGGGPGGGGGGGGT',
      'TGPPPPPPPPPPPPPPPPPPPGGT',
      'TGPGGGGGGPPPPPPGGGGGPGGT',
      'TGPGGGGGGPPPPPPGGGGGPGGT',
      'TGPGGGGGGPPPPPPGGGGGPGGT',
      'TGPGTTTTGPPPPPPGTTTGPGGT',
      'TGPGTTTTGGPPPPGGTTTGPGGT',
      'TGPGTTTTGGGPPGGGTTTGPGGT',
      'TGPGGGGGGGGPPGGGGGGGPGGT',
      'TGPPPPPPPPPPPPPPPPPPPGGT',
      'TGTTTTTTGGGPPGGGGGGGGGGT',
      'TGTTTTTTGGGPPGGGGGGGGGGT',
      'TGTTTTTTGTTPPGGGGGGGGGGT',
      'TGTTTTTTGTTPPGGWWWWWGGGT',
      'TGTTTTTTGTTPPGGWWWWWWGGT',
      'TGGGGGGGGTTPPGGWWWWWWGGT',
      'TGGGGGGGGGGPPGGWWWWWGGGT',
      'TGGGGGGGGGGPPGGGWWWGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'n1_sign', kind: 'sign', x: 10, y: 28, emoji: '🪧', text: 'Meadowcross Village — where every tale begins. The Old Mill woodland lies north.' },
      { id: 'n1_greeter', kind: 'npc', x: 13, y: 10, sprite: 'assets/npc-trainers/cafe-courier/cafe-courier.png', name: 'Cafe Courier', text: 'Welcome to Meadowcross! Wild monsters hide in the tall grass — paths are safe.' },
      { id: 'n1_scout', kind: 'trainer', x: 2, y: 10, sprite: 'assets/npc-trainers/trail-scout/trail-scout.png', facing: 'right', sightRange: 4,
        name: 'Trail Scout', team: [{ s: 'field_mouse', lvl: 4 }, { s: 'street_pup', lvl: 5 }], text: 'Every trail teaches you something!' },
    ],
    warps: [
      { x: 11, y: 0, toMap: 'normal_2', toX: 11, toY: 30 },
      { x: 12, y: 0, toMap: 'normal_2', toX: 12, toY: 30 },
      { x: 11, y: 31, toMap: '@exit' },
      { x: 12, y: 31, toMap: '@exit' },
    ],
  },
  normal_2: {
    id: 'normal_2', name: 'Oldmill Woodland', region: 'normal',
    width: 24, height: 32, bg: 'assets/region-maps/type/normal/oldmill-woodland/oldmill-woodland.png',
    entry: { x: 11, y: 30 },
    ground: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TGGGGGGGGGGGGGGGGGGGGGGT',
      'TGTTTGGGGPPGGGGGGGTTTGGT',
      'TGTTTGGGGPPGGGGGGGTTTGGT',
      'TGGGGGGGGPPGGGGGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPPPPPPPPPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGTTGGGGPPGGWWGGGPGTTGT',
      'TGGTTGGGGPPGGWWGGGPGTTGT',
      'TGGGGGGGGPPPPPPPPPPGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPGGWWGGGGGGGGT',
      'TGGGGGGGGPPPPPPPPPPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPGGWWGGGPGGGGT',
      'TGGGGGGGGPPPGGGGGGPGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'n2_sign', kind: 'sign', x: 10, y: 29, emoji: '🪧', text: 'Oldmill Woodland — the mill wheel still turns. The Meadow Dojo trial is held here.' },
      { id: 'n2_hiker', kind: 'trainer', x: 18, y: 22, sprite: 'assets/npc-trainers/mountain-hiker/mountain-hiker.png', facing: 'left', sightRange: 4,
        name: 'Mountain Hiker', team: [{ s: 'stripe_ferret', lvl: 6 }, { s: 'soft_cap_bear', lvl: 7 }], text: 'These woods keep you on your toes!' },
      { id: 'dojo_normal', kind: 'dojo', x: 12, y: 4, dojoId: 'normal', name: 'Elder Naturalist',
        text: 'The Meadow Dojo trial awaits — show me how you and your monsters have grown!' },
      { id: 'boss_normal', kind: 'boss', x: 5, y: 12, bossRegion: 'normal', name: 'Apex Chimera',
        text: 'A monstrous chimera blocks the clearing!' },
    ],
    warps: [
      { x: 11, y: 31, toMap: 'normal_1', toX: 11, toY: 1 },
      { x: 12, y: 31, toMap: 'normal_1', toX: 12, toY: 1 },
    ],
  },

  // ---------- FIGHTING — Central Dojo Heartland ----------
  fighting_1: {
    id: 'fighting_1', name: 'Dojo Valley', region: 'fighting',
    width: 24, height: 32, bg: 'assets/region-maps/type/fighting/dojo-valley/dojo-valley.png',
    entry: { x: 11, y: 29 },
    ground: [
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGTTTTGGGGGPPGGGGGTTTTGT',
      'TGTTTTGGGGGPPGGGGGTTTTGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGWWGGGGGGPPGGGGGGWWGGT',
      'TGGWWGGGGGGPPGGGGGGWWGGT',
      'TGGGWWGGGGGPPGGGGGWWGGGT',
      'TGGGWWGGGGGPPGGGGGWWGGGT',
      'TGGGGWWGGGGPPGGGGWWGGGGT',
      'TGGGGGWWGGGPPGGGWWGGGGGT',
      'TGGGGGGWWGGPPGGWWGGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGPPPPPPPPPPGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGWWWGGGGGPPGGGGGGGGGGT',
      'TGGWWWGGGGGPPGGGGTTTGGGT',
      'TGGGGGGGGGGPPGGGGTTTGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'f1_sign', kind: 'sign', x: 10, y: 27, emoji: '🪧', text: 'Dojo Valley — cross the training plaza to reach the Champion Colosseum up north.' },
      { id: 'f1_dancer', kind: 'trainer', x: 14, y: 21, sprite: 'assets/npc-trainers/street-dancer/street-dancer.png', facing: 'left', sightRange: 4,
        name: 'Street Dancer', team: [{ s: 'kick_chick', lvl: 13 }, { s: 'jab_pup', lvl: 14 }], text: 'Footwork wins fights — watch mine!' },
    ],
    warps: [
      { x: 11, y: 0, toMap: 'fighting_2', toX: 11, toY: 30 },
      { x: 12, y: 0, toMap: 'fighting_2', toX: 12, toY: 30 },
      { x: 11, y: 31, toMap: '@exit' },
      { x: 12, y: 31, toMap: '@exit' },
    ],
  },
  fighting_2: {
    id: 'fighting_2', name: 'Champion Colosseum', region: 'fighting',
    width: 24, height: 32, bg: 'assets/region-maps/type/fighting/champion-colosseum/champion-colosseum.png',
    entry: { x: 11, y: 30 },
    ground: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPTTTTTPPPPPPPPTTTTTTPPT',
      'TPTTTTTPPPPPPPPTTTTTTPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPTTTTPPPPPPPPPTTTTTPPT',
      'TPPTTTTPPPPPPPPPTTTTTPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPTTTTTPPPPTTTTTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTPPPPPPPPPPPPTPPPPT',
      'TPPPPTTTTTPPPPTTTTTPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPTTTTTPPPPPPPPTTTTPPPT',
      'TPPTTTTTPPPPPPPPTTTTPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'f2_prefect', kind: 'trainer', x: 3, y: 5, sprite: 'assets/npc-trainers/school-prefect/school-prefect.png', facing: 'down', sightRange: 3,
        name: 'School Prefect', team: [{ s: 'belt_beetle', lvl: 16 }, { s: 'palm_mole', lvl: 17 }], text: 'Discipline beats raw strength every time.' },
      { id: 'dojo_fighting', kind: 'dojo', x: 12, y: 20, dojoId: 'fighting', name: 'Martial Student',
        text: 'The Valor Dojo trial is fought in the grand arena. Step up!' },
      { id: 'boss_fighting', kind: 'boss', x: 12, y: 14, bossRegion: 'fighting', name: 'Warfist Behemoth',
        text: 'The arena champion beast pounds its fists!' },
    ],
    warps: [
      { x: 11, y: 31, toMap: 'fighting_1', toX: 11, toY: 1 },
      { x: 12, y: 31, toMap: 'fighting_1', toX: 12, toY: 1 },
    ],
  },

  // ---------- PSYCHIC — Northeast Observatory ----------
  psychic_1: {
    id: 'psychic_1', name: 'Dreamglass Sanctum', region: 'psychic',
    width: 24, height: 32, bg: 'assets/region-maps/type/psychic/dreamglass-sanctum/dreamglass-sanctum.png',
    entry: { x: 11, y: 29 },
    ground: [
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTCCCPPCCCTTTTTTTT',
      'TTTTTTTCCCCPPCCCCTTTTTTT',
      'TTTTTTTCCCCPPCCCCTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTTTPTTTTTTPPTTTTTTPTTTT',
      'TTTTPTTTTTTPPTTTTTTPTTTT',
      'TTTTPTTTTTTPPTTTTTTPTTTT',
      'TTTTPTTTTTTPPTTTTTTPTTTT',
      'TTTTPTTTTTTPPTTTTTTPTTTT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPPPT',
      'TCCTTTTTTTTPPTTTTTTTTCCT',
      'TCCTTTTTTTTPPTTTTTTTTCCT',
      'TCCTTTTTTTTPPTTTTTTTTCCT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTCCCPPCCCTTTTTTTT',
      'TTTTTTTTCCCPPCCCTTTTTTTT',
      'TTTTTTTTCCCPPCCCTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'p1_sign', kind: 'sign', x: 11, y: 24, emoji: '🪧', text: 'Dreamglass Sanctum — walkways float over a sea of dreams. Mind the edge.' },
      { id: 'p1_arch', kind: 'trainer', x: 2, y: 15, sprite: 'assets/npc-trainers/ruin-archaeologist/ruin-archaeologist.png', facing: 'right', sightRange: 4,
        name: 'Ruin Archaeologist', team: [{ s: 'spoon_mite', lvl: 19 }, { s: 'rune_owl', lvl: 20 }], text: 'These ruins whisper to those who listen.' },
    ],
    warps: [
      { x: 11, y: 0, toMap: 'psychic_2', toX: 11, toY: 30 },
      { x: 12, y: 0, toMap: 'psychic_2', toX: 12, toY: 30 },
      { x: 11, y: 31, toMap: '@exit' },
      { x: 12, y: 31, toMap: '@exit' },
    ],
  },
  psychic_2: {
    id: 'psychic_2', name: 'Mindwave Observatory', region: 'psychic',
    width: 24, height: 32, bg: 'assets/region-maps/type/psychic/mindwave-observatory/mindwave-observatory.png',
    entry: { x: 11, y: 30 },
    ground: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTPPPPPPTTTTTTTTT',
      'TTTTTTTTTPPPPPPTTTTTTTTT',
      'TTTTTTTTTPPPPPPTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTCPPPPPPPPPPPPPPPPCTTT',
      'TTTCPPTTTTTTTTTTTTPPCTTT',
      'TTTTPPTTTTTTTTTTTTPPTTTT',
      'TTTTPPTTTTTTTTTTTTPPTTTT',
      'TTTTPPTTPPPPPPPPTTPPTTTT',
      'TTTTPPTTPPPPPPPPTTPPTTTT',
      'TTTTPPTTPPPTTPPPTTPPTTTT',
      'TTTTPPTTPPPTTPPPTTPPTTTT',
      'TTTTPPTTPPPTTPPPTTPPTTTT',
      'TTTTPPTTPPPPPPPPTTPPTTTT',
      'TTTTPPTTPPPPPPPPTTPPTTTT',
      'TTTTPPPPPPPPPPPPPPPPTTTT',
      'TTTTPPTTTTTTTTTTTTPPTTTT',
      'TTTTPPTTTTTTTTTTTTPPTTTT',
      'TTTCPPTTTTTTTTTTTTPPCTTT',
      'TTTCPPPPPPPPPPPPPPPPCTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'p2_inventor', kind: 'trainer', x: 4, y: 21, sprite: 'assets/npc-trainers/young-inventor/young-inventor.png', facing: 'up', sightRange: 3,
        name: 'Young Inventor', team: [{ s: 'pulse_jelly', lvl: 22 }, { s: 'dream_tapir', lvl: 23 }], text: 'My gadgets read brainwaves — yours are noisy!' },
      { id: 'dojo_psychic', kind: 'dojo', x: 10, y: 3, dojoId: 'psychic', name: 'Stage Magician',
        text: 'The Mind Dojo trial bends more than spoons. Ready?' },
      { id: 'boss_psychic', kind: 'boss', x: 9, y: 15, bossRegion: 'psychic', name: 'Astral Eye Hierophant',
        text: 'A vast eye turns its gaze upon you!' },
    ],
    warps: [
      { x: 11, y: 31, toMap: 'psychic_1', toX: 11, toY: 1 },
      { x: 12, y: 31, toMap: 'psychic_1', toX: 12, toY: 1 },
    ],
  },

  // ---------- ICE — Northern Frostlands ----------
  ice_1: {
    id: 'ice_1', name: 'Frostglass Tundra', region: 'ice',
    width: 24, height: 32, bg: 'assets/region-maps/element/ice/frostglass-tundra/frostglass-tundra.png',
    entry: { x: 11, y: 29 },
    ground: [
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGCCGGGGGGPPGGGGGGGGGGT',
      'TGGCCGGGWWWWWWWWWWGGGGGT',
      'TGGGGGGGWWWWWWWWWWWWGGGT',
      'TGGGGGGGWWWWWWWWWWWWGGGT',
      'TGGGGGGGWWWWWWWWWWWWGGGT',
      'TGGGGGGGWWWWWWWWWWGGGGGT',
      'TGGGGGGGGWWWWWWWWGGGPGGT',
      'TGPPPPPPGGGGGGGGGGGPPGGT',
      'TGPGGGGGGGGGGGGGGGGPGGGT',
      'TGPGGGGGGGGGGGGGGGGPGGGT',
      'TGPPPPPPPPPPPPPPPPPPGGGT',
      'TGGGGGGGGGGGPGGGGGGGGGGT',
      'TGGGGGGGGGGGPGGGGGGGGGGT',
      'TGGGGGGGGGGGPGGGGGGGGGGT',
      'TGGGGGGGGGGGPGGGGGGGGGGT',
      'TGGGWWWWGGGGPGGGGGGCCGGT',
      'TGGWWWWWWGGGPGGGGGGCCGGT',
      'TGGWWWWWWGGGPGGGGGGGGGGT',
      'TGGWWWWWWGGGPGGGGGGGGGGT',
      'TGGWWWWWWGGGPGGGGGGGGGGT',
      'TGGGWWWWGGGGPGGGGGGGGGGT',
      'TGGGGGGGGGGGPGGGGGGGGGGT',
      'TGGGGGGGGGGGPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TGGGGGGGGGGPPGGGGGGGGGGT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'i1_sign', kind: 'sign', x: 10, y: 27, emoji: '🪧', text: 'Frostglass Tundra — frozen lakes crack underfoot. The Glacier Palace crowns the north.' },
      { id: 'i1_chef', kind: 'trainer', x: 16, y: 14, sprite: 'assets/npc-trainers/traveling-chef/traveling-chef.png', facing: 'left', sightRange: 4,
        name: 'Traveling Chef', team: [{ s: 'icicle_crab', lvl: 25 }, { s: 'slush_seal', lvl: 26 }], text: 'Fresh snow crab! After our battle, that is.' },
    ],
    warps: [
      { x: 11, y: 0, toMap: 'ice_2', toX: 11, toY: 30 },
      { x: 12, y: 0, toMap: 'ice_2', toX: 12, toY: 30 },
      { x: 11, y: 31, toMap: '@exit' },
      { x: 12, y: 31, toMap: '@exit' },
    ],
  },
  ice_2: {
    id: 'ice_2', name: 'Glacier Palace', region: 'ice',
    width: 24, height: 32, bg: 'assets/region-maps/element/ice/glacier-palace/glacier-palace.png',
    entry: { x: 11, y: 30 },
    ground: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTCCCCCCCCTTTTTTTT',
      'TTTTTTTTCCCCCCCCTTTTTTTT',
      'TTTTTTTTCCCCCCCCTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTCCCCPPPPPPPPPPPPCCCCTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTCCCCTTTTTPPTTTTTCCCCTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTCCCCCCCPPCCCCCCCTTTT',
      'TTTTCCCCCCCPPCCCCCCCTTTT',
      'TTTTCCCCCCCPPCCCCCCCTTTT',
      'TTTTCCCCCCCPPCCCCCCCTTTT',
      'TTTTCCCCCCCPPCCCCCCCTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTWWWWTTTTTPPTTTTTWWWWTT',
      'TTWWWWTTTTTPPTTTTTWWWWTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'i2_drummer', kind: 'trainer', x: 10, y: 13, sprite: 'assets/npc-trainers/punk-drummer/punk-drummer.png', facing: 'right', sightRange: 3,
        name: 'Punk Drummer', team: [{ s: 'snow_fox', lvl: 28 }, { s: 'rime_owl', lvl: 29 }], text: 'The echo in this hall? Best drum sound ever.' },
      { id: 'dojo_ice', kind: 'dojo', x: 10, y: 2, dojoId: 'ice', name: 'Snow Ranger',
        text: 'The Frost Dojo trial is held in the throne hall. Don\'t slip.' },
      { id: 'boss_ice', kind: 'boss', x: 14, y: 14, bossRegion: 'ice', name: 'Absolute Zero Leviathan',
        text: 'The palace guardian coils, radiating deadly cold!' },
    ],
    warps: [
      { x: 11, y: 31, toMap: 'ice_1', toX: 11, toY: 1 },
      { x: 12, y: 31, toMap: 'ice_1', toX: 12, toY: 1 },
    ],
  },

  // ---------- DRAGON — Northwest Mountains ----------
  dragon_1: {
    id: 'dragon_1', name: 'Wyrmstone Highlands', region: 'dragon',
    width: 24, height: 32, bg: 'assets/region-maps/type/dragon/wyrmstone-highlands/wyrmstone-highlands.png',
    entry: { x: 11, y: 29 },
    ground: [
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCTTTTCCCCCPPCCCCTTTTCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCTTTTTTTTPPTTTTTTTTCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TPPPPPPPPPPPPPPPPPPPPCCT',
      'TPCCCCCCCCCCCCCCCCCCPCCT',
      'TPCCCCCCCCCCCCCCCCCCPCCT',
      'TPCTTTTTTTTTTTTTTTTCPCCT',
      'TPCCCCCCCCCCCCCCCCCCPCCT',
      'TPPPPPPPPPPPPPPPPPPPPCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCTTTCCCCCPPCCCCCTTTCCT',
      'TCCTTTCCCCCPPCCCCCTTTCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCTTCCCCPPCCCCTTCCCCT',
      'TCCCCTTCCCCPPCCCCTTCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'd1_sign', kind: 'sign', x: 10, y: 25, emoji: '🪧', text: 'Wyrmstone Highlands — dragon country. The Skyfang Caldera waits at the summit.' },
      { id: 'd1_foreman', kind: 'trainer', x: 13, y: 16, sprite: 'assets/npc-trainers/quarry-foreman/quarry-foreman.png', facing: 'left', sightRange: 4,
        name: 'Quarry Foreman', team: [{ s: 'pebble_drake', lvl: 31 }, { s: 'copper_dragonet', lvl: 32 }], text: 'These stones remember when dragons ruled!' },
    ],
    warps: [
      { x: 11, y: 0, toMap: 'dragon_2', toX: 11, toY: 30 },
      { x: 12, y: 0, toMap: 'dragon_2', toX: 12, toY: 30 },
      { x: 11, y: 31, toMap: '@exit' },
      { x: 12, y: 31, toMap: '@exit' },
    ],
  },
  dragon_2: {
    id: 'dragon_2', name: 'Skyfang Caldera', region: 'dragon',
    width: 24, height: 32, bg: 'assets/region-maps/type/dragon/skyfang-caldera/skyfang-caldera.png',
    entry: { x: 11, y: 30 },
    ground: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTCCCCCCTTTTTTTTT',
      'TTTTTTTTTCCCCCCTTTTTTTTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TTWWWTTTTTTPPTTTTTTWWWTT',
      'TTWWWTTTTTTPPTTTTTTWWWTT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCWWCCCCCCCPPCCCCCCCWWCT',
      'TCWWCCCCCCCPPCCCCCCCWWCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCPPPPPPPPPPCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCWWWCCCCCCPPCCCCCCWWWCT',
      'TCWWWCCCCCCPPCCCCCCWWWCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TCCCCCCCCCCPPCCCCCCCCCCT',
      'TTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    npcs: [
      { id: 'd2_courier', kind: 'trainer', x: 3, y: 22, sprite: 'assets/npc-trainers/night-courier/night-courier.png', facing: 'right', sightRange: 4,
        name: 'Night Courier', team: [{ s: 'mist_wyrmling', lvl: 36 }, { s: 'thorn_dragonet', lvl: 37 }], text: 'I deliver even through dragonfire!' },
      { id: 'dojo_dragon', kind: 'dojo', x: 9, y: 12, dojoId: 'dragon', name: 'Dragon Guardian',
        text: 'The Wyrm Dojo trial is fought in the caldera ring. Prove your worth!' },
      { id: 'boss_dragon', kind: 'boss', x: 14, y: 15, bossRegion: 'dragon', name: 'Voidcrown Bahamut',
        text: 'The king of the caldera unfurls its wings!' },
      { id: 'champion_npc', kind: 'champion', x: 11, y: 2, name: 'Veteran Champion',
        sprite: 'assets/npc-trainers/veteran-champion/veteran-champion.png',
        text: 'Only a trainer holding all five badges may face me.' },
    ],
    warps: [
      { x: 11, y: 31, toMap: 'dragon_1', toX: 11, toY: 1 },
      { x: 12, y: 31, toMap: 'dragon_1', toX: 12, toY: 1 },
    ],
  },
};

// Region entry: which map the player lands in when travelling to a region from the world map.
const REGION_ENTRY_MAP = {
  normal: 'normal_1', fighting: 'fighting_1', psychic: 'psychic_1', ice: 'ice_1', dragon: 'dragon_1',
};
